"use client";
import "./globals.css";
import "/styles/fonts.css";

import { Inter } from "next/font/google";
import { Providers } from "/app/Providers.jsx";
import CustomNavbar from "@/components/CustomNavbar";
import { ThemeProvider } from "@emotion/react";
import "tailwindcss/tailwind.css";
import Footer from "@/components/Footer";

const theme = {
  colors: {
    primary: "#2c272b",
    secondary: "#592c33",
    secondaryDarker: "#472429",
    transparentSecondary: "#592c334a",
    black: "#2e2c2e",
    foreground: "#fdfdfd",
    foregroundDarker: "#d1d1d1",
    darkText: "#212427",
    gray: "#a6a4a4",
    cardBackground: "#eeeeee",
    bgDark: "#202124",
  },
};
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Donbufalo",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    // <Provider store={store}>
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body className={inter.className}>
          <CustomNavbar />

          <Providers>
            <main>{children}</main>
          </Providers>
          <Footer />
        </body>
      </html>
    </ThemeProvider>
    // </Provider>
  );
}
